### ISSUE TITLE
Auto Mod Crashes and Errors

### ISSUE THREAD

**Issue by DJPanda065** [architdate/PKHeX-Auto-Legality-Mod#23]
Auto Mod crashes with Kommo-o and it can't seem to make a legal Lunala or Naganadel either.

Kommo-o
Ability: Bulletproof
EVs: 252 HP / 252 Atk / 4 SpA
Brave Nature
- Drain Punch
- Clanging Scales
- Fire Punch
- False Swipe

Nebby (Lunala) @ Master Ball
Ability: Shadow Shield
EVs: 252 HP / 252 SpA / 4 SpD
Modest Nature
IVs: 0 Atk
- Moongeist Beam
- Dazzling Gleam
- Calm Mind
- Ice Beam

Naganadel @ Poison Barb
Ability: Beast Boost
Shiny: Yes
EVs: 252 SpA / 4 SpD / 252 Spe
Timid Nature
IVs: 0 Atk
- Nasty Plot
- Heat Wave
- Dragon Pulse
- Sludge Bomb

System.NullReferenceException: Object reference not set to an instance of an object.
   at PKHeX.Core.ShowdownSet.ConvertFormFromShowdown(String form, Int32 spec, Int32 ability) in C:\Users\JGame\Desktop\Games\Pokemon\Auto PkHex setup\PKHeX-master\PKHeX-master\PKHeX.Core\PKM\ShowdownSet.cs:line 429
   at PKHeX.Core.ShowdownSet..ctor(String input) in C:\Users\JGame\Desktop\Games\Pokemon\Auto PkHex setup\PKHeX-master\PKHeX-master\PKHeX.Core\PKM\ShowdownSet.cs:line 149
   at PKHeX.WinForms.Main.ClickShowdownImportPKM(Object sender, EventArgs e) in C:\Users\JGame\Desktop\Games\Pokemon\Auto PkHex setup\PKHeX-master\PKHeX-master\PKHeX.WinForms\MainWindow\Main.cs:line 454
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by architdate** [comment]
@DJPanda065 Kommo-o seems to be a PKHeX standard showdown import issue, I would recommend that you open the issue for Kommo-o there. I will put out a fix for Lunala and Naganadel however.
